---
global-config:
  # Title to display in titlebar
  window-title: "Door Dog - Universal RFID Scanner system"
  # Image to display in background of each window
  background-image:
    path: "assets/images/doordog_white.png"
    ratio: 1
  background-color: "#000000"
  foreground-color: "#ffffff"
  # Message to display on each window
  message: "Please scan here!"
  # Monitors settings
  monitors:
    count: 2
    default-resolution:
      width: 1920
      height: 1080
    fullscreen: true
  # Scanner devices settings
  devices:
    names:
      - "Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader"
  # Alerts settings (Feedback on API responses)
  alerts:
    success:
      # support wav or ogg
      sound: "assets/audio/good_1.wav"
      background-color: "#00ff00"
      foreground-color: "#000000"
    error:
      # support wav or ogg
      sound: "assets/audio/bad_1.wav"
      background-color: "#ff0000"
      foreground-color: "#000000"
  # Endpoint API to poke when scanning new tag and receive a result to display
  endpoints:
    post-scan: "https://lanets.ca/health"
    post-logs: "https://lanets.ca/health"
  # Blocked Tags will always display an error and will not post to endpoint
  # Especially usefull to test behaviours before using in production
  blocked-tags: ["22211722"]
